# Generated by Django 4.1 on 2022-12-04 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash_on_delivery', 'cash_on_delivery'), ('stripe', 'stripe'), ('paypal', 'paypal')], max_length=30)),
                ('payment_status', models.CharField(choices=[('initiated', 'initiated'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('rejected', 'rejected'), ('failed', 'failed'), ('paid', 'paid')], max_length=30)),
                ('transaction_number', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='orders.order')),
            ],
        ),
    ]
