# Generated by Django 4.1 on 2022-12-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discount_type',
            field=models.CharField(choices=[('flat', 'flat'), ('percentage', 'percentage')], default='flat', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_value',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
    ]
